# RTL-SDR V4 WinUSB Driver Installer
# Автоматическая установка WinUSB драйвера через pnputil

Write-Host "=== RTL-SDR V4 Driver Installer ===" -ForegroundColor Cyan
Write-Host ""

# Проверка прав администратора
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "ERROR: Запустите скрипт от имени администратора!" -ForegroundColor Red
    Write-Host "Right-click PowerShell -> Run as Administrator" -ForegroundColor Yellow
    exit 1
}

# Поиск RTL-SDR устройства
Write-Host "[1/4] Поиск RTL-SDR устройства..." -ForegroundColor Yellow
$devices = Get-PnpDevice -Class USB -ErrorAction SilentlyContinue | Where-Object {
    $_.FriendlyName -like "*RTL*" -or
    $_.FriendlyName -like "*Realtek*" -or
    $_.FriendlyName -like "*DVB*" -or
    $_.FriendlyName -like "*Digital*" -or
    $_.InstanceID -like "*VID_0BDA*"
}

if ($devices.Count -eq 0) {
    Write-Host "WARNING: RTL-SDR устройство не найдено!" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Возможные причины:" -ForegroundColor Yellow
    Write-Host "  - Устройство не подключено" -ForegroundColor Yellow
    Write-Host "  - Сбой USB-дескриптора (попробуйте другой порт/кабель)" -ForegroundColor Yellow
    Write-Host "  - Требуется ручная установка через Zadig" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Скачать Zadig: https://zadig.akeo.ie/" -ForegroundColor Cyan
    Write-Host ""
    
    # Показать все USB устройства с VID 0BDA (Realtek)
    Write-Host "Поиск всех Realtek USB устройств..." -ForegroundColor Yellow
    $allRealtek = Get-PnpDevice -Class USB -ErrorAction SilentlyContinue | Where-Object {
        $_.InstanceID -like "*VID_0BDA*"
    }
    if ($allRealtek) {
        Write-Host "Найдены Realtek устройства:" -ForegroundColor Green
        $allRealtek | Format-Table FriendlyName, Status, InstanceID -AutoSize
    }
    exit 1
}

Write-Host "Найдено устройств: $($devices.Count)" -ForegroundColor Green
$devices | Format-Table FriendlyName, Status, InstanceID -AutoSize

# Проверка статуса
$problemDevices = $devices | Where-Object { $_.Status -ne "OK" }
if ($problemDevices.Count -gt 0) {
    Write-Host ""
    Write-Host "WARNING: Устройства с проблемами:" -ForegroundColor Yellow
    $problemDevices | Format-Table FriendlyName, Status, ProblemDescription -AutoSize
    
    $choice = Read-Host "`nПродолжить установку драйвера? (y/n)"
    if ($choice -ne 'y' -and $choice -ne 'Y') {
        Write-Host "Отменено пользователем" -ForegroundColor Yellow
        exit 0
    }
}

# Создание INF файла для WinUSB
Write-Host ""
Write-Host "[2/4] Создание INF файла..." -ForegroundColor Yellow

$infDir = "$env:TEMP\rtl-sdr-winusb"
New-Item -ItemType Directory -Force -Path $infDir | Out-Null

$infContent = @'
; RTL-SDR V4 WinUSB Driver
; Generated by install_rtlsdr_driver.ps1

[Version]
Signature = "$Windows NT$"
Class = USBDevice
ClassGUID = {88BAE032-5A81-49f0-BC3D-A4FF138216D6}
Provider = %ProviderString%
CatalogFile = rtl-sdr-winusb.cat
DriverVer = 04/12/2026,1.0.0.0

[Manufacturer]
%ManufacturerName% = Devices,NTamd64

[Devices.NTamd64]
%DeviceDescription% = USB_Install, USB\VID_0BDA&PID_2838
%DeviceDescription% = USB_Install, USB\VID_0BDA&PID_2832

[USB_Install]
Include = winusb.inf
Needs = WINUSB.NT

[USB_Install.Services]
Include = winusb.inf
AddService = WinUSB,0x00000002,WinUSB_ServiceInstall

[WinUSB_ServiceInstall]
DisplayName = %WinUSB_SvcDesc%
ServiceType = 1
StartType = 3
ErrorControl = 1
ServiceBinary = %12%\WinUSB.sys

[USB_Install.Wdf]
KmdfService = WINUSB, WinUsb_Install

[WinUSB_Install]
KmdfLibraryVersion = 1.15

[USB_Install.HW]
AddReg = Dev_AddReg

[Dev_AddReg]
HKR,,DeviceInterfaceGUIDs,0x10000,"{00000000-0000-0000-0000-000000000000}"

[Strings]
ProviderString = "RTL-SDR"
ManufacturerName = "RTL-SDR"
DeviceDescription = "RTL-SDR V4 WinUSB"
WinUSB_SvcDesc = "WinUSB Driver"
'@

$infPath = "$infDir\rtl-sdr-winusb.inf"
$infContent | Out-File -FilePath $infPath -Encoding ascii

Write-Host "INF файл создан: $infPath" -ForegroundColor Green

# Установка драйвера
Write-Host ""
Write-Host "[3/4] Установка драйвера..." -ForegroundColor Yellow

$result = pnputil /add-driver $infPath /install 2>&1
$result | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }

if ($LASTEXITCODE -eq 0) {
    Write-Host "Драйвер успешно установлен!" -ForegroundColor Green
} else {
    Write-Host "WARNING: pnputil вернул код $LASTEXITCODE" -ForegroundColor Yellow
    Write-Host "Возможно драйвер уже установлен или требуется ручная установка" -ForegroundColor Yellow
}

# Пересканирование устройств
Write-Host ""
Write-Host "[4/4] Пересканирование устройств..." -ForegroundColor Yellow

# Отключаем и включаем устройства
foreach ($device in $devices) {
    $instanceId = $device.InstanceID
    Write-Host "  Перезапуск: $($device.FriendlyName)" -ForegroundColor Gray
    
    Disable-PnpDevice -InstanceId $instanceId -Confirm:$false -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
    Enable-PnpDevice -InstanceId $instanceId -Confirm:$false -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
}

# Проверка результата
Write-Host ""
Write-Host "=== Результат ===" -ForegroundColor Cyan
$updatedDevices = Get-PnpDevice -Class USB -ErrorAction SilentlyContinue | Where-Object {
    $_.FriendlyName -like "*RTL*" -or
    $_.FriendlyName -like "*Realtek*" -or
    $_.FriendlyName -like "*DVB*" -or
    $_.FriendlyName -like "*Digital*" -or
    $_.InstanceID -like "*VID_0BDA*"
}

if ($updatedDevices) {
    $updatedDevices | Format-Table FriendlyName, Status, Class -AutoSize
    
    $okDevices = $updatedDevices | Where-Object { $_.Status -eq "OK" }
    if ($okDevices.Count -gt 0) {
        Write-Host ""
        Write-Host "SUCCESS: RTL-SDR V4 готов к работе!" -ForegroundColor Green
        Write-Host "Проверьте в SDR# — устройство должно появиться в списке" -ForegroundColor Cyan
    } else {
        Write-Host ""
        Write-Host "WARNING: Устройства всё ещё с ошибками" -ForegroundColor Yellow
        Write-Host "Попробуйте:" -ForegroundColor Yellow
        Write-Host "  1. Отключить и подключить устройство" -ForegroundColor Yellow
        Write-Host "  2. Использовать Zadig для ручной установки" -ForegroundColor Yellow
        Write-Host "  3. Попробовать другой USB порт" -ForegroundColor Yellow
    }
} else {
    Write-Host "Устройства не найдены после установки" -ForegroundColor Red
}

Write-Host ""
Write-Host "=== Готово ===" -ForegroundColor Cyan
